services:
  database:
    build:
      context: ./database
    container_name: postgres-db
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build:
      context: ./backend-api
      dockerfile: Dockerfile
    container_name: backend-api-student
    depends_on:
      - database
    networks:
      - app-network

  httpd:
    build:
      context: ./http-server
      dockerfile: Dockerfile
    container_name: http-server
    ports:
      - "8084:80"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  dbdata:

networks:
  app-network:
